version: "3.3"

services:
  cuben-client:
    container_name: cuben-client
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    environment:
      - PORT=3000

    volumes:
      - ./:/usr/src/cuben-client
    working_dir: /usr/src/cuben-client
    
    networks:
      - client-network

    # FOR PRODUCTION 
    command: bash -c "yarn && yarn run build && yarn run start"
  
networks:
  client-network:
    driver: bridge